---
# tasks file for hnakamur.anyenv
- include: anyenv.yml
  tags: [anyenv_initial_setup]

- shell: >
    anyenv install {{ item }}
    creates={{ anyenv_install_dir }}/envs/{{ item }}
  with_items:
    - rbenv
    - ndenv
  tags: [anyenv_install_envs]

- include: rbenv-version.yml
  when: anyenv_rbenv_version != ""

- include: env-version.yml anyenv_env_name=ndenv anyenv_env_version="{{ anyenv_ndenv_version }}"
  when: anyenv_ndenv_version != ""
