---
# tasks file for hnakamur.anyenv
- include: anyenv.yml
  tags: [anyenv_initial_setup]

- include: env.yml anyenv_env_name=rbenv anyenv_env_version="{{ anyenv_rbenv_version }}"
  when: anyenv_rbenv_version != ""

- include: env.yml anyenv_env_name=ndenv anyenv_env_version="{{ anyenv_ndenv_version }}"
  when: anyenv_ndenv_version != ""
