---
- include: env-version.yml anyenv_env_name=ndenv anyenv_env_version={{ anyenv_ndenv_version }}

- npm: name={{ item }} global=yes executable={{ anyenv_install_dir }}/envs/ndenv/shims/npm
  with_items: anyenv_ndenv_global_packages

- shell: >
    "{{ anyenv_install_dir | replace('~', '$HOME') }}/envs/ndenv/bin/ndenv" rehash
