- homebrew: name={{ item }} state=latest
  with_items:
    - readline
    - openssl

- include: >
    env-version.yml anyenv_env_name=rbenv anyenv_env_version={{ anyenv_rbenv_version }}

- shell: >
    "{{ anyenv_install_dir | replace('~', '$HOME') }}/envs/rbenv/shims/gem" install {{ item }}
  with_items: anyenv_rbenv_global_gems

- shell: >
    "{{ anyenv_install_dir | replace('~', '$HOME') }}/envs/rbenv/bin/rbenv" rehash
