- homebrew: update_homebrew=yes

- homebrew: name={{ item }} state=latest
  with_items:
    - readline
    - openssl

- include: >
    env-version.yml anyenv_env_name=rbenv anyenv_env_version={{ anyenv_rbenv_version }}
